//
//  generatedNumbersStatistics.hpp
//  Run
//
//  Created by Radovan Klembara on 04/12/2020.
//

#ifndef generatedNumbersStatistics_hpp
#define generatedNumbersStatistics_hpp

#include <iostream>
#include <string>
#include <vector>
#include "StatisticsOutput.hpp"
#include <climits>

#define RANDOM 0
#define EXP 1
#define NORM 2
#define UNIFORM 3


/// Structure for saving info about generated values generated by one function.
struct GeneratedNumberInfo {
    std::string name;
    unsigned long long generated;
    double min;
    double max;
    double sum;
    
    /// Constructor of generated number info.
    /// @param name of function which generates values
    GeneratedNumberInfo(std::string name);
    
    /// Computes standard deviations of values.
    double standard_deviation();
    
    /// Computes avarege value.
    double avg_val();
};

/// Class for saving info about all generated values
class GeneratedNumberStatistics: public Stat{
public:
    GeneratedNumberStatistics();
    std::vector<GeneratedNumberInfo> generated_numbers_info{};
    void print_out() override;
    
    void add_value(unsigned short type, double value);
    
};


#endif /* generatedNumbersStatistics_hpp */
