test1:
	#g++ -g -std=c++17 main.cpp numberGenerator.cpp eventClass.cpp identifiable.cpp priorityQueue.cpp resourcePromiseClass.cpp simSimulatorClass.cpp simulationStatistics.cpp facilityClass.cpp -o test
	g++ -g -std=c++17 *.cpp -o test
