test1:
	g++ -std=c++17 -o test1 main.cpp numberGenerator.cpp eventClass.cpp identifiable.cpp priorityQueue.cpp resourcePromiseClass.cpp simSimulatorClass.cpp simulationStatistics.cpp facilityClass.cpp
